title:             CS50 Puyo
email:             m@mathsistor.com
description:       A Blog for CS50 Puyo
author:            M Vargas
baseurl:           ""
url:               "http://cs50puyo.tk"

# Social Profiles
twitter_username:  lmiguelvargasf
github_username:   lmiguelvargasf
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
